![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [2]:
my_array = np.arange(10)
print(my_array)
print(my_array[9:0:-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print(my_array[2:0:-1]) # No sale el 0 y si lo cambio a -1 pega error. Podria crear un nuevo array de esos valores

[2 1]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
my_matrix = np.arange(1,21,1).reshape(5,4)
print(my_matrix)
matrix_inversa = my_matrix[::-1]
print(matrix_inversa)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[17 18 19 20]
 [13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [3]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
loros = x[x == "Loro"]
print(loros)

indices = np.where(x == "Loro")[0]
loros2 = x[indices]
print(loros2)

['Loro' 'Loro']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [4]:
secuencia = np.arange(20)
array = secuencia.reshape(2,5,2)
print(array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [36]:
array10 = np.zeros(10)
print(array10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
array10[3] = 1
print(array10)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [35]:
vector11 = np.arange(10,50)
print(vector11)
vector_invert = np.flip(vector11)
print(vector_invert)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [33]:
matriz13 = np.random.randint(0,51, size = (10,10))
minimo = np.min(matriz13)
maximo = np.max(matriz13)
print(matriz13)
print(minimo)
print(maximo)

[[18 35 36 31 25  3 33 13 24  9]
 [18 32 46 11 18 26 37 33 21 32]
 [ 5 12  4 36 46 47 15  2 46 23]
 [11  1 46 19 15  5 15 46  0 48]
 [20 42 13 16 25 46 42 39 19 47]
 [35 46  2 48  7 15 45 11 23 29]
 [38 36 39 24  1 28 26 33 33 13]
 [ 7 35  9 31  7 41 37 25 15 44]
 [41 46  0  7 42 30 20 15 16 21]
 [39  9  8 33 10 48 28  2  7 39]]
0
48


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [32]:
vector = np.random.randint(0,51, size = 30)
media = np.mean(vector)
print(vector)
print(media)

[43 33 42 44  3 42 31 16 34 38 46 45 36 32  6 26 17 42 26 46  2 26 36 27
 27 48 44 49 48  2]
31.9


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [30]:
matriz = np.zeros((8,8), dtype = int)
print(matriz)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [31]:
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            matriz[i,j] = 1
print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [19]:
matriz = np.random.rand(5,5)
print(matriz)
print({np.mean(matriz)})
print({np.std(matriz)})

[[0.65410019 0.87807946 0.86235286 0.91538421 0.32398044]
 [0.4994725  0.98140594 0.32025757 0.54992157 0.8216325 ]
 [0.34956467 0.77879877 0.33476603 0.91409703 0.60371156]
 [0.94242655 0.8552172  0.48712744 0.03598724 0.36758552]
 [0.44898197 0.11876999 0.83119754 0.02628239 0.2814523 ]]
{np.float64(0.5673021378591279)}
{np.float64(0.293455366034354)}


In [20]:
media = np.mean(matriz)
desv_std = np.std(matriz)
matriz_normalizada = (matriz - media) / desv_std
print(matriz_normalizada)

[[ 0.29577941  1.05902758  1.00543646  1.18614997 -0.82916084]
 [-0.23114124  1.41113044 -0.84184717 -0.05922731  0.86667477]
 [-0.74197813  0.72071142 -0.79240707  1.18176368  0.12407142]
 [ 1.27830141  0.98112046 -0.27320916 -1.81054757 -0.68056897]
 [-0.40319646 -1.52845102  0.8992693  -1.84361852 -0.97408284]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [8]:
array = np.arange(0,11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
array2 = array.copy()
mask = (array >= 3) & (array <= 8)
array2[mask] = -1
print(array2)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [ ]:
# No entiendo a que se refiere con negar, si se refiere a no mostrar los numeros, a que sean el número que corresponde en negativo o si quiere que devuelvan False